In [2]:
import numpy as np

In [3]:
a = np.array([[ 0, 1, 2, 3, 4],[ 5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

(3, 5)
2
15
int32
4


In [5]:
b=np.arange(15).reshape(3,5)
print(b)

c= np.arange(20)
c.shape = (4,5)
print(c)

d = np.array( [ [1,2], [3,4] ], dtype=complex )
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [23]:
f = np.zeros((3,4))
print(f)

g = np.ones((3,4))
print(g)

h = np.empty((2,3))
print(h)

h = np.empty((4,4))
print(h)

#To create a sequence of numbers (specify that it should move by 5)
i = np.arange( 10, 50, 5 )
print(i)

#To create a sequence of numbers (specify that you need just 6 sequence)
j = np.linspace( 10, 50, 6 )
print(j)

#To create a sequence of numbers (specify that you need just 6 sequence)
k = np.sin(1/2)
print(k)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10. 18. 26.]
 [34. 42. 50.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.56038300e-307]
 [1.42418987e-306 1.37961641e-306 1.60220528e-306 1.24611266e-306]
 [9.34598925e-307 1.24612081e-306 1.11260755e-306 1.60220393e-306]
 [1.51320640e-306 9.34609790e-307 1.86921279e-306 1.24610723e-306]]
[10 15 20 25 30 35 40 45]
[10. 18. 26. 34. 42. 50.]
0.479425538604203


In [29]:
#Random
l = np.random.random((2,3))
print(l)

m = np.random.normal(1.50, 0.20, 5)
print(m)

[[0.2168386  0.8216993  0.23407363]
 [0.01046955 0.15467252 0.72891864]]
[1.25387848 1.77916121 1.57120608 1.07321716 1.57587181]


In [32]:
#Multiplying Matrices
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0],[3,4]] )

print(A*B)
print(A.dot(B))
print(np.dot(A,B))
print(A@B)

#Modifying Numpy arrays
A*=5
print(A)

A += 10
print(A)

A +=B
print(A)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 5]
 [0 5]]
[[15 15]
 [10 15]]
[[17 15]
 [13 19]]


In [8]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum()) # total sum
print(b.sum(axis=0))# sum column wise
print(b.sum(axis=1))# sum row wise
print(b.cumsum(axis=0))# sum column wise

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [17]:
a= np.array([ 0, 1, 8, 27, 64, 125, 216, 343, 512, 729])
a[:0:2] #The third parameter specifies step
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [20]:
def f(x,y):
    return 10*x+y
# b = np.fromfunction(f,(5,4),dtype=int)
b = np.fromfunction(lambda i, j: i - j, (3, 3), dtype=int)
b

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])